apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: relayer-ingress
  namespace: ika-tensei
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.ikatensei.xyz
      secretName: relayer-tls
  rules:
    - host: api.ikatensei.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: relayer
                port:
                  number: 3001
