[toolchain]
anchor = "0.30.1"
rust = "1.70.0"

[features]
default = []
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]

[programs.localnet]
ika-tensei-reborn = "GaF33RCjTAW6cGCWaiefEVuptbsDDDSAtNx3ipDmNqnj"

[programs.devnet]
ika-tensei-reborn = "GaF33RCjTAW6cGCWaiefEVuptbsDDDSAtNx3ipDmNqnj"

[programs.mainnet-beta]
ika-tensei-reborn = "GaF33RCjTAW6cGCWaiefEVuptbsDDDSAtNx3ipDmNqnj"

[provider]
cluster = "mainnet"
wallet = " ~/.config/solana/id.json"

[workspace]
members = [
    "programs/*"
]
