[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/ika_tensei"]
resolver = "2"

[programs.localnet]
ika_tensei = "mbEQvaiUYdc65Qz4rd67oBY1LbSCBq1Da8Y1MciwtPa"

[programs.devnet]
ika_tensei = "mbEQvaiUYdc65Qz4rd67oBY1LbSCBq1Da8Y1MciwtPa"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json ./tests/**/*.ts"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true
